apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.clusterName }}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["{{ .Values.serviceSubnet }}"]
    pods:
      cidrBlocks: ["{{ .Values.podSubnet }}"]
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: {{ .Values.clusterName }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ .Values.clusterName }}-control-plane

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlaneEndpoint.host }}
    port: {{ .Values.controlPlaneEndpoint.port }}
  noCloudProvider: {{ .Values.noCloudProvider }}

---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.clusterName }}-control-plane
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.controlPlaneReplicas }}
  version: {{ .Values.kubernetesVersion }}
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3Machine
      name: {{ .Values.clusterName }}-control-plane
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Machine
metadata:
  name: {{ .Values.clusterName }}-control-plane
  namespace: {{ .Values.namespace }}
spec:
  image:
    url: {{ .Values.metal3.image.url }}
    checksum: {{ .Values.metal3.image.checksum }}
  hostSelector:
    matchLabels:
      metal3.io/role: control-plane

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.clusterName }}-md-0
  namespace: {{ .Values.namespace }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ .Values.clusterName }}
    cluster.x-k8s.io/role: worker
spec:
  clusterName: {{ .Values.clusterName }}
  replicas: {{ .Values.workerReplicas }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ .Values.clusterName }}
      cluster.x-k8s.io/role: worker
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ .Values.clusterName }}
        cluster.x-k8s.io/role: worker
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.clusterName }}-md-0
      clusterName: {{ .Values.clusterName }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3Machine
        name: {{ .Values.clusterName }}-md-0
      version: {{ .Values.kubernetesVersion }}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Machine
metadata:
  name: {{ .Values.clusterName }}-md-0
  namespace: {{ .Values.namespace }}
spec:
  image:
    url: {{ .Values.metal3.image.url }}
    checksum: {{ .Values.metal3.image.checksum }}
  hostSelector:
    matchLabels:
      metal3.io/role: worker

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.clusterName }}-md-0
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external 